fix init script, maybe mod conflict in minetest_game?

diff --git a/root/custom-cont-init.d/cap-init b/root/custom-cont-init.d/cap-init
--- a/root/custom-cont-init.d/cap-init
+++ b/root/custom-cont-init.d/cap-init
@@ -1,5 +1,13 @@
 #!/usr/bin/with-contenv bash
 
+if [ -z "$DEBUG" ]; 
+    then echo ""; 
+    else
+        echo "------------- ENVIRONMENT VARIABLES -----------------------------";
+        printenv;
+        echo "------------------------------------------";
+fi
+
 # replace values in /config/.minetest/${GAME}/minetest.conf by environment variables
 
 echo "------------------------------------------"
@@ -7,12 +15,12 @@ echo "------------------------------------------"
 CONF_PATH="/config/.minetest/games/${GAME}/minetest.conf"
 
 if [ -z "$CONF_PATH" ]; 
-    then echo "CONF_PATH not given"; 
+    then echo "[ERROR] CONF_PATH not given"; 
     echo "------------------------------------------"
-    exit;
+    exit 1;
 fi
 
-echo "replace/add values in ${CONF_PATH} by environment variables"
+echo "[INFO] replace/add values in ${CONF_PATH} by environment variables"
 
 ### example for replacement if environment variable is given ###
 # server_name
@@ -89,11 +97,72 @@ echo "world_start_time = 6125" >> $CONF_PATH;
 # mapgen
 if [ -z "$MAPGEN" ]; 
     then echo "[INFO] MAPGEN not given"; 
-    echo "mg_name = $MAPGEN" >> $CONF_PATH;
+    else echo "mg_name = $MAPGEN" >> $CONF_PATH;
 fi
 
-# permissions
-#chown -R abc:abc \
- #   /config
+if [ -z "$DEBUG" ]; 
+    then echo ""; 
+    else
+        echo "------------------------------------------";
+        echo "[INFO] $CONF_PATH";
+        echo "------------------------------------------";
+        cat $CONF_PATH;
+        echo "------------------------------------------";
+fi
 
 echo "------------------------------------------"
+
+# add mods and config only to default game, not to tutorial
+if [ "$GAME" = "tutorial" ]; 
+    then echo "[INFO] do not copy mods in tutorial game"; 
+    exit;
+fi
+
+MOD_PATH="/config/.minetest/games/${GAME}"
+
+if [ -z "$MOD_PATH" ]; 
+    then echo "[ERROR] MOD_PATH not given"; 
+    echo "------------------------------------------";
+    exit 1;
+fi
+
+if [ ! -d "$MOD_PATH" ]; then
+  echo "[ERROR] $MOD_PATH does not exist.";
+  exit 1;
+fi
+
+echo "----- [INFO] /home/mods -------------------------------------"
+ls /home/mods
+echo "------------------------------------------"
+
+if [ -z "$DEBUG" ]; 
+    then echo ""; 
+    else
+        echo "------------------------------------------";
+        echo "[INFO] $MOD_PATH/mods before copy";
+        echo "------------------------------------------";
+        ls $MOD_PATH/mods;
+        echo "------------------------------------------";
+fi
+
+
+echo "[INFO] copy mods from /home/mods to ${MOD_PATH}";
+cp -R /home/mods ${MOD_PATH};
+
+if [ -z "$DEBUG" ]; 
+    then echo ""; 
+    else
+        echo "------------------------------------------";
+        echo "[INFO] $MOD_PATH/mods";
+        echo "------------------------------------------";
+        ls $MOD_PATH/mods;
+        echo "------------------------------------------";
+fi
+
+echo "------------------------------------------"
+
+echo "ls /config/.minetest/worlds/world"
+ls /config/.minetest/worlds/world
+
+echo "ls /config/.minetest/games/${GAME}/"
+ls /config/.minetest/games/${GAME}/
